---
# The version of the cluster-monitoring repo to check out. See commits:
# https://github.com/carlosedp/cluster-monitoring/commits/master
cluster_monitoring_version: 40c9318

# Whether to force updating the cluster-monitoring repository. Set this to true
# if you change the cluster_monitoring_version above.
cluster_monitoring_update_repo: false

grafana_from_email: myemail@example.com
