---
- name: Check current node_exporter version.
  command: "{{ node_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: node_exporter_version_check

- name: Download and unarchive node_exporter into temporary location.
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    remote_src: true
  when: >
    node_exporter_version_check.stdout is not defined
    or node_exporter_version not in node_exporter_version_check.stdout

- name: Move node_exporter binary into place.
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart node_exporter

- name: Create node_exporter user.
  user:
    name: node_exporter
    shell: /sbin/nologin
    state: present

- name: Copy the node_exporter systemd unit file.
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  register: node_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart node_exporter
  when: node_exporter_service is changed

- name: Ensure node_exporter is running and enabled at boot.
  service:
    name: node_exporter
    state: "{{ node_exporter_state }}"
    enabled: "{{ node_exporter_enabled }}"

- name: Verify node_exporter is responding to requests.
  uri:
    url: http://localhost:9100/
    return_content: yes
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
